---
abstract: 'coordinate multi-object mech tests for multi-user web app testing'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4202, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-WWW-Mechanize-MultiMech
provides:
  Test::WWW::Mechanize::MultiMech:
    file: lib/Test/WWW/Mechanize/MultiMech.pm
    version: 1.002
requires:
  Carp: 1.26
  Test::Builder: 0.99
  Test::WWW::Mechanize: 1.44
  perl: 5.006
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 1.002
